/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FaceDetectTest */

#ifndef _Included_FaceDetectTest
#define _Included_FaceDetectTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FaceDetectTest
 * Method:    loadFaceDetector
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_FaceDetectTest_loadFaceDetector
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     FaceDetectTest
 * Method:    findFaces
 * Signature: (II[B[I)J
 */
JNIEXPORT jlong JNICALL Java_FaceDetectTest_findFaces
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
